//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long ID { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public byte TypeId { get; set; }
        public byte StatusId { get; set; }
        public long PatientId { get; set; }
    
        public virtual AppointmentStatus AppointmentStatus { get; set; }
        public virtual AppointmentType AppointmentType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
