//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public short ID { get; set; }
        public string ISOName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
